os: Visual Studio 2017
platform: x64

test: off

install:
  - git submodule update --init --recursive

#
# Build
#
build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - msbuild Vision.sln
  - ctest
  - cd ..