dist: xenial
language: cpp
script: eval "CC=gcc-7 && CXX=g++-7" && mkdir -p build && cd build && cmake .. && make Vision
compiler: gcc
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-7
